# Setup
title:               Juan Pablo Bertucci
tagline:             'Transport and statistics'
description:         'An attempt at a blog'
url:                 https://jpchomp.github.io
baseurl:             '/lanyon'
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              JP
  url:               https://twitter.com/jpchomp
  email:             bertuccijuanpablo@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-210023023-1
