# Setup
title:               Juan Pablo Bertucci
tagline:             'Trying this out'
description:         'A cool dude'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Juan Pablo Bertucci
  url:               https://twitter.com/jpchomp
  email:             bertuccijuanpablo@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
